server:
  port: "8000"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "auth_dev"

smtp:
  host: "smtp.localhost.com"
  port: "587"
  username: "smtp_user"
  password: "smtp_password"

jwt:
  secret: "your_secret_key"
