services:
  postgres:
    image: postgres:16.3-alpine3.19
    container_name: auth_dev
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - auth

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_mercado_dev
    platform: linux/amd64
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - type: volume
        source: mailhog_data
        target: /home/mailhog

networks:
  auth:
    driver: bridge

volumes:
  auth_db_data:
  mailhog_data:
